#ifndef CPU6502_HPP
#define CPU6502_HPP

#include "fullinstruction.hpp"

#include <spdlog/spdlog.h>

#include <cmath>
#include <bitset>
#include <string>
#include <stack>
#include <array>
#include <algorithm>
#include <memory>
#include <limits>

constexpr double CLOCK_SPEED_MHZ = 1.789773;
constexpr std::uint16_t MEM_SIZE = 2048;
constexpr std::uint8_t STACK_SIZE = 255;
constexpr std::uint8_t INSTRUCTION_COUNT = 255;

class CPU6502
{
public:
	CPU6502();
	void fetch_fullinstruction(const std::uint8_t &op_code);
	void decode_instruction(const std::uint16_t &operand);
	void exec_instruction(const std::uint16_t &address);
	void clear();
	virtual ~CPU6502();

	void set_mem(const std::shared_ptr<std::array<std::uint8_t, MEM_SIZE>> &mem);
	void nes_init_regs();

private:
	/* registers: accumulator, x index, y index, stack pointer, status register, program counter
	   status register: bit 5 can not be changed and is always set to 1.
	   | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0 |
	   | N | V | - | B | D | I | Z | C | */
	std::uint8_t acc, ix, iy, sp, sr;
	std::uint16_t pc;

	std::stack<std::uint8_t> stack;
	std::shared_ptr<std::array<std::uint8_t, MEM_SIZE>> mem;

	FULLINSTRUCTION current_instruction;

	/* instruction matrix from https://www.masswerk.at/6502/6502_instruction_set.html
	   lines that are commented out are illegal. likely to be replaced with
	   INSTRUCTION::ILL and ADDRMODE::ILL in the future. */
	const std::array<FULLINSTRUCTION, INSTRUCTION_COUNT> instr_matrix = {
		FULLINSTRUCTION
		{ 0x00, INSTRUCTION::BRK, ADDRMODE::IMP, 1, 7 },
		{ 0x01, INSTRUCTION::ORA, ADDRMODE::INX, 2, 6 },
		//		{ 0x02, nullptr, nullptr },
		//		{ 0x03, nullptr, nullptr },
		//		{ 0x04, nullptr, nullptr },
		{ 0x05, INSTRUCTION::ORA, ADDRMODE::ZPG, 2, 3 },
		{ 0x06, INSTRUCTION::ASL, ADDRMODE::ZPG, 2, 5 },
		//		{ 0x07, nullptr, nullptr },
		{ 0x08, INSTRUCTION::PHP, ADDRMODE::IMP, 1, 3 },
		{ 0x09, INSTRUCTION::ORA, ADDRMODE::IMM, 2, 2 },
		{ 0x0A, INSTRUCTION::ASL, ADDRMODE::ACC, 0, 2 },
		//		{ 0x0B, nullptr, nullptr },
		//		{ 0x0C, nullptr, nullptr },
		{ 0x0D, INSTRUCTION::ORA, ADDRMODE::ABS, 3, 4 },
		{ 0x0E, INSTRUCTION::ASL, ADDRMODE::ABS, 3, 6 },
		//		{ 0x0F, nullptr, nullptr },
		{ 0x10, INSTRUCTION::BPL, ADDRMODE::REL, 2, 2 },
		{ 0x11, INSTRUCTION::ORA, ADDRMODE::INY, 2, 5 },
		//		{ 0x12, nullptr, nullptr },
		//		{ 0x13, nullptr, nullptr },
		//		{ 0x14, nullptr, nullptr },
		{ 0x15, INSTRUCTION::ORA, ADDRMODE::ZPX, 2, 4 },
		{ 0x16, INSTRUCTION::ASL, ADDRMODE::ZPX, 2, 6 },
		//		{ 0x17, nullptr, nullptr },
		{ 0x18, INSTRUCTION::CLC, ADDRMODE::IMP, 1, 2 },
		{ 0x19, INSTRUCTION::ORA, ADDRMODE::ABY, 3, 4 },
		//		{ 0x1A, nullptr, nullptr },
		//		{ 0x1B, nullptr, nullptr },
		//		{ 0x1C, nullptr, nullptr },
		{ 0x1D, INSTRUCTION::ORA, ADDRMODE::ABX, 3, 4 },
		{ 0x1E, INSTRUCTION::ASL, ADDRMODE::ABX, 3, 7 },
		//		{ 0x1F, nullptr, nullptr },
		{ 0x20, INSTRUCTION::JSR, ADDRMODE::ABS, 3, 6 },
		{ 0x21, INSTRUCTION::AND, ADDRMODE::INX, 2, 6 },
		//		{ 0x22, nullptr, nullptr },
		//		{ 0x23, nullptr, nullptr },
		{ 0x24, INSTRUCTION::BIT, ADDRMODE::ZPG, 2, 3 },
		{ 0x25, INSTRUCTION::AND, ADDRMODE::ZPG, 2, 3 },
		{ 0x26, INSTRUCTION::ROL, ADDRMODE::ZPG, 2, 5 },
		//		{ 0x27, nullptr, nullptr },
		{ 0x28, INSTRUCTION::PLP, ADDRMODE::IMP, 1, 4 },
		{ 0x29, INSTRUCTION::AND, ADDRMODE::IMM, 2, 2 },
		{ 0x2A, INSTRUCTION::ROL, ADDRMODE::ACC, 0, 2 },
		//		{ 0x2B, nullptr, nullptr },
		{ 0x2C, INSTRUCTION::BIT, ADDRMODE::ABS, 3, 4 },
		{ 0x2D, INSTRUCTION::AND, ADDRMODE::ABS, 3, 4 },
		{ 0x2E, INSTRUCTION::ROL, ADDRMODE::ABS, 3, 6 },
		//		{ 0x2F, nullptr, nullptr },
		{ 0x30, INSTRUCTION::BMI, ADDRMODE::REL, 2, 2 },
		{ 0x31, INSTRUCTION::AND, ADDRMODE::INY, 2, 5 },
		//		{ 0x32, nullptr, nullptr },
		//		{ 0x33, nullptr, nullptr },
		//		{ 0x34, nullptr, nullptr },
		{ 0x35, INSTRUCTION::AND, ADDRMODE::ZPX, 2, 4 },
		{ 0x36, INSTRUCTION::ROL, ADDRMODE::ZPX, 2, 6 },
		//		{ 0x37, nullptr, nullptr },
		{ 0x38, INSTRUCTION::SEC, ADDRMODE::IMP, 1, 2 },
		{ 0x39, INSTRUCTION::AND, ADDRMODE::ABY, 3, 4 },
		//		{ 0x3A, nullptr, nullptr },
		//		{ 0x3B, nullptr, nullptr },
		//		{ 0x3C, nullptr, nullptr },
		{ 0x3D, INSTRUCTION::AND, ADDRMODE::ABX, 3, 4 },
		{ 0x3E, INSTRUCTION::ROL, ADDRMODE::ABX, 3, 7 },
		//		{ 0x3F, nullptr, nullptr },
		{ 0x40, INSTRUCTION::RTI, ADDRMODE::IMP, 1, 6 },
		{ 0x41, INSTRUCTION::EOR, ADDRMODE::INX, 2, 6 },
		//		{ 0x42, nullptr, nullptr },
		//		{ 0x43, nullptr, nullptr },
		//		{ 0x44, nullptr, nullptr },
		{ 0x45, INSTRUCTION::EOR, ADDRMODE::ZPG, 2, 3 },
		{ 0x46, INSTRUCTION::LSR, ADDRMODE::ZPG, 2, 5 },
		//		{ 0x47, nullptr, nullptr },
		{ 0x48, INSTRUCTION::PHA, ADDRMODE::IMP, 1, 3 },
		{ 0x49, INSTRUCTION::EOR, ADDRMODE::IMM, 2, 2 },
		{ 0x4A, INSTRUCTION::LSR, ADDRMODE::ACC, 0, 2 },
		//		{ 0x4B, nullptr, nullptr },
		{ 0x4C, INSTRUCTION::JMP, ADDRMODE::ABS, 3, 3 },
		{ 0x4D, INSTRUCTION::EOR, ADDRMODE::ABS, 3, 4 },
		{ 0x4E, INSTRUCTION::LSR, ADDRMODE::ABS, 3, 6 },
		//		{ 0x4F, nullptr, nullptr },
		{ 0x50, INSTRUCTION::BVC, ADDRMODE::REL, 2, 2 },
		{ 0x51, INSTRUCTION::EOR, ADDRMODE::INY, 2, 5 },
		// { 0x52, nullptr, nullptr },
		// { 0x53, nullptr, nullptr },
		// { 0x54, nullptr, nullptr },
		{ 0x55, INSTRUCTION::EOR, ADDRMODE::ZPX, 2, 4 },
		{ 0x56, INSTRUCTION::LSR, ADDRMODE::ZPX, 2, 6 },
		// { 0x57, nullptr, nullptr },
		{ 0x58, INSTRUCTION::CLI, ADDRMODE::IMP, 1, 2 },
		{ 0x59, INSTRUCTION::EOR, ADDRMODE::ABY, 3, 4 },
		// { 0x5A, nullptr, nullptr },
		// { 0x5B, nullptr, nullptr },
		// { 0x5C, nullptr, nullptr },
		{ 0x5D, INSTRUCTION::EOR, ADDRMODE::ABX, 3, 4 },
		{ 0x5E, INSTRUCTION::LSR, ADDRMODE::ABX, 3, 7 },
		// { 0x5F, nullptr, nullptr },
		{ 0x60, INSTRUCTION::RTS, ADDRMODE::IMP, 1, 6 },
		{ 0x61, INSTRUCTION::ADC, ADDRMODE::INX, 2, 6 },
		// { 0x62, nullptr, nullptr },
		// { 0x63, nullptr, nullptr },
		// { 0x64, nullptr, nullptr },
		{ 0x65, INSTRUCTION::ADC, ADDRMODE::ZPG, 2, 3 },
		{ 0x66, INSTRUCTION::ROR, ADDRMODE::ZPG, 2, 5 },
		// { 0x67, nullptr, nullptr },
		{ 0x68, INSTRUCTION::PLA, ADDRMODE::IMP, 1, 4 },
		{ 0x69, INSTRUCTION::ADC, ADDRMODE::IMM, 2, 2 },
		{ 0x6A, INSTRUCTION::ROR, ADDRMODE::ACC, 0, 2 },
		// { 0x6B, nullptr, nullptr },
		{ 0x6C, INSTRUCTION::JMP, ADDRMODE::IND, 5 },
		{ 0x6D, INSTRUCTION::ADC, ADDRMODE::ABS, 3, 4 },
		{ 0x6E, INSTRUCTION::ROR, ADDRMODE::ABS, 3, 6 },
		// { 0x6F, nullptr, nullptr },
		{ 0x70, INSTRUCTION::BVC, ADDRMODE::REL, 2, 2 },
		{ 0x71, INSTRUCTION::ADC, ADDRMODE::INY, 2, 5 },
		// { 0x72, nullptr, nullptr },
		// { 0x73, nullptr, nullptr },
		// { 0x74, nullptr, nullptr },
		{ 0x75, INSTRUCTION::ADC, ADDRMODE::ZPX, 2, 4 },
		{ 0x76, INSTRUCTION::ROR, ADDRMODE::ZPX, 2, 6 },
		// { 0x77, nullptr, nullptr },
		{ 0x78, INSTRUCTION::SEI, ADDRMODE::IMP, 1, 2 },
		{ 0x79, INSTRUCTION::ADC, ADDRMODE::ABY, 3, 4 },
		// { 0x7A, nullptr, nullptr },
		// { 0x7B, nullptr, nullptr },
		// { 0x7C, nullptr, nullptr },
		{ 0x7D, INSTRUCTION::ADC, ADDRMODE::ABX, 3, 4 },
		{ 0x7E, INSTRUCTION::ROR, ADDRMODE::ABX, 3, 7 },
		// { 0x7F, nullptr, nullptr },
		// { 0x80, nullptr, nullptr },
		{ 0x81, INSTRUCTION::STA, ADDRMODE::INX, 2, 6 },
		// { 0x82, nullptr, nullptr },
		// { 0x83, nullptr, nullptr },
		{ 0x84, INSTRUCTION::STY, ADDRMODE::ZPG, 2, 3 },
		{ 0x85, INSTRUCTION::STA, ADDRMODE::ZPG, 2, 3 },
		{ 0x86, INSTRUCTION::STX, ADDRMODE::ZPG, 2, 3 },
		// { 0x87, nullptr, nullptr },
		{ 0x88, INSTRUCTION::DEY, ADDRMODE::IMP, 1, 2 },
		// { 0x89, nullptr, nullptr },
		{ 0x8A, INSTRUCTION::TXA, ADDRMODE::IMP, 1, 2 },
		// { 0x8B, nullptr, nullptr },
		{ 0x8C, INSTRUCTION::STY, ADDRMODE::ABS, 3, 4 },
		{ 0x8D, INSTRUCTION::STA, ADDRMODE::ABS, 3, 4 },
		{ 0x8E, INSTRUCTION::STX, ADDRMODE::ABS, 3, 4 },
		// { 0x8F, nullptr, nullptr },
		{ 0x90, INSTRUCTION::BCC, ADDRMODE::REL, 2, 2 },
		{ 0x91, INSTRUCTION::STA, ADDRMODE::INY, 2, 6 },
		// { 0x92, nullptr, nullptr },
		// { 0x93, nullptr, nullptr },
		{ 0x94, INSTRUCTION::STY, ADDRMODE::ZPX, 2, 4 },
		{ 0x95, INSTRUCTION::STA, ADDRMODE::ZPX, 2, 4 },
		{ 0x96, INSTRUCTION::STX, ADDRMODE::ZPY, 2, 4 },
		// { 0x97, nullptr, nullptr },
		{ 0x98, INSTRUCTION::TYA, ADDRMODE::IMP, 1, 2 },
		{ 0x99, INSTRUCTION::STA, ADDRMODE::ABY, 3, 5 },
		{ 0x9A, INSTRUCTION::TXS, ADDRMODE::IMP, 1, 2 },
		// { 0x9B, nullptr, nullptr },
		// { 0x9C, nullptr, nullptr },
		{ 0x9D, INSTRUCTION::STA, ADDRMODE::ABX, 3, 5 },
		// { 0x9E, nullptr, nullptr },
		// { 0x9F, nullptr, nullptr },
		{ 0xA0, INSTRUCTION::LDY, ADDRMODE::IMM, 2, 2 },
		{ 0xA1, INSTRUCTION::LDA, ADDRMODE::INX, 2, 6 },
		{ 0xA2, INSTRUCTION::LDX, ADDRMODE::IMM, 2, 2 },
		// { 0xa3, nullptr, nullptr },
		{ 0xA4, INSTRUCTION::LDY, ADDRMODE::ZPG, 2, 3 },
		{ 0xA5, INSTRUCTION::LDA, ADDRMODE::ZPG, 2, 3 },
		{ 0xA6, INSTRUCTION::LDX, ADDRMODE::ZPG, 2, 3 },
		// { 0xa7, nullptr, nullptr },
		{ 0xA8, INSTRUCTION::TAY, ADDRMODE::IMP, 1, 2 },
		{ 0xA9, INSTRUCTION::LDA, ADDRMODE::IMM, 2, 2 },
		{ 0xAA, INSTRUCTION::TAX, ADDRMODE::IMP, 1, 2 },
		// { 0xAB, nullptr, nullptr },
		{ 0xAC, INSTRUCTION::LDY, ADDRMODE::ABS, 3, 4 },
		{ 0xAD, INSTRUCTION::LDA, ADDRMODE::ABS, 3, 4 },
		{ 0xAE, INSTRUCTION::LDX, ADDRMODE::ABS, 3, 4 },
		// { 0xAF, nullptr, nullptr },
		{ 0xB0, INSTRUCTION::BCS, ADDRMODE::REL, 2, 2 },
		{ 0xB1, INSTRUCTION::LDA, ADDRMODE::INY, 2, 5 },
		// { 0xB2, nullptr, nullptr },
		// { 0xB3, nullptr, nullptr },
		{ 0xB4, INSTRUCTION::LDY, ADDRMODE::ZPX, 2, 4 },
		{ 0xB5, INSTRUCTION::LDA, ADDRMODE::ZPX, 2, 4 },
		{ 0xB6, INSTRUCTION::LDX, ADDRMODE::ZPY, 2, 4 },
		// { 0xB7, nullptr, nullptr },
		{ 0xB8, INSTRUCTION::CLV, ADDRMODE::IMP, 1, 2 },
		{ 0xB9, INSTRUCTION::LDA, ADDRMODE::ABY, 3, 4 },
		{ 0xBA, INSTRUCTION::TSX, ADDRMODE::IMP, 1, 2 },
		// { 0xBB, nullptr, nullptr },
		{ 0xBC, INSTRUCTION::LDY, ADDRMODE::ABX, 3, 4 },
		{ 0xBD, INSTRUCTION::LDA, ADDRMODE::ABX, 3, 4 },
		{ 0xBE, INSTRUCTION::LDX, ADDRMODE::ABY, 3, 4 },
		// { 0xBF, nullptr, nullptr },
		{ 0xC0, INSTRUCTION::CPY, ADDRMODE::IMM, 2, 2 },
		{ 0xC1, INSTRUCTION::CMP, ADDRMODE::INX, 2, 6 },
		// { 0xC2, nullptr, nullptr },
		// { 0xC3, nullptr, nullptr },
		{ 0xC4, INSTRUCTION::CPY, ADDRMODE::ZPG, 2, 3 },
		{ 0xC5, INSTRUCTION::CMP, ADDRMODE::ZPG, 2, 3 },
		{ 0xC6, INSTRUCTION::DEC, ADDRMODE::ZPG, 2, 5 },
		// { 0xC7, nullptr, nullptr },
		{ 0xC8, INSTRUCTION::INY, ADDRMODE::IMP, 1, 2 },
		{ 0xC9, INSTRUCTION::CMP, ADDRMODE::IMM, 2, 2 },
		{ 0xCA, INSTRUCTION::DEX, ADDRMODE::IMP, 1, 2 },
		// { 0xCB, nullptr, nullptr },
		{ 0xCC, INSTRUCTION::CPY, ADDRMODE::ABS, 3, 4 },
		{ 0xCD, INSTRUCTION::CMP, ADDRMODE::ABS, 3, 4 },
		{ 0xCE, INSTRUCTION::DEC, ADDRMODE::ABS, 3, 6 },
		// { 0xCF, nullptr, nullptr },
		{ 0xD0, INSTRUCTION::BNE, ADDRMODE::REL, 2, 2 },
		{ 0xD1, INSTRUCTION::CMP, ADDRMODE::INY, 2, 5 },
		// { 0xD2, nullptr, nullptr },
		// { 0xD3, nullptr, nullptr },
		// { 0xD4, nullptr, nullptr },
		{ 0xD5, INSTRUCTION::CMP, ADDRMODE::ZPX, 2, 4 },
		{ 0xD6, INSTRUCTION::DEC, ADDRMODE::ZPX, 2, 6 },
		// { 0xD7, nullptr, nullptr },
		{ 0xD8, INSTRUCTION::CLD, ADDRMODE::IMP, 1, 2 },
		{ 0xD9, INSTRUCTION::CMP, ADDRMODE::ABY, 3, 4 },
		// { 0xDA, nullptr, nullptr },
		// { 0xDB, nullptr, nullptr },
		// { 0xDC, nullptr, nullptr },
		{ 0xDD, INSTRUCTION::CMP, ADDRMODE::ABX, 3, 4 },
		{ 0xDE, INSTRUCTION::DEC, ADDRMODE::ABX, 3, 7 },
		// { 0xDF, nullptr, nullptr },
		{ 0xE0, INSTRUCTION::CPX, ADDRMODE::IMM, 2, 2 },
		{ 0xE1, INSTRUCTION::SBC, ADDRMODE::INX, 2, 6 },
		// { 0xE2, nullptr, nullptr },
		// { 0xE3, nullptr, nullptr },
		{ 0xE4, INSTRUCTION::CPX, ADDRMODE::ZPG, 2, 3 },
		{ 0xE5, INSTRUCTION::SBC, ADDRMODE::ZPG, 2, 3 },
		{ 0xE6, INSTRUCTION::INC, ADDRMODE::ZPG, 2, 5 },
		// { 0xE7, nullptr, nullptr },
		{ 0xE8, INSTRUCTION::INX, ADDRMODE::IMP, 1, 2 },
		{ 0xE9, INSTRUCTION::SBC, ADDRMODE::IMM, 2, 2 },
		{ 0xEA, INSTRUCTION::NOP, ADDRMODE::IMP, 1, 2 },
		// { 0xEB, nullptr, nullptr },
		{ 0xEC, INSTRUCTION::CPX, ADDRMODE::ABS, 3, 4 },
		{ 0xED, INSTRUCTION::SBC, ADDRMODE::ABS, 3, 4 },
		{ 0xEE, INSTRUCTION::INC, ADDRMODE::ABS, 3, 6 },
		// { 0xEF, nullptr, nullptr },
		{ 0xF0, INSTRUCTION::BEQ, ADDRMODE::REL, 2, 2 },
		{ 0xF1, INSTRUCTION::SBC, ADDRMODE::INY, 2, 5 },
		// { 0xF2, nullptr, nullptr },
		// { 0xF3, nullptr, nullptr },
		// { 0xF4, nullptr, nullptr },
		{ 0xF5, INSTRUCTION::SBC, ADDRMODE::ZPX, 2, 4 },
		{ 0xF6, INSTRUCTION::INC, ADDRMODE::ZPX, 2, 6 },
		// { 0xF7, nullptr, nullptr },
		{ 0xF8, INSTRUCTION::SED, ADDRMODE::IMP, 1, 2 },
		{ 0xF9, INSTRUCTION::SBC, ADDRMODE::ABY, 3, 4 },
		// { 0xFA, nullptr, nullptr },
		// { 0xFB, nullptr, nullptr },
		// { 0xFC, nullptr, nullptr },
		{ 0xFD, INSTRUCTION::SBC, ADDRMODE::ABX, 3, 4 },
		{ 0xFE, INSTRUCTION::INC, ADDRMODE::ABX, 3, 7 },
	};
};

#endif
